---
title: "HW2"
author: "Gemma G Clark"
date: "Fall 2020"
output: html_document
---

## Problem 1
###### I added the operating system I am using to the demographics.txt file.


## Problem 2a
```{r}
# Show the equations that need solving
print('Solve the equations:')
print('2x + 5y = 33')
print('x + 3y = 19')

# Use matrix algebra to solve the equations
A <- matrix(c(2,1,5,3), nrow = 2, ncol = 2)
b <- matrix(c(33,19), nrow = 2, ncol = 1)
answer <- solve(A,b)
x <- answer[1]
y <- answer[2]

# Print answers
print(c('x = ', x))
print(c('y = ', y))

```

## Problem 2b
```{r}
# Create a vector with values ranging from 1 to 100
  # I like integers so I'm going to floor the random values
  # I'm creating a random vector length (somewhere between 1 and 50) too
v <- floor(runif(floor(runif(1,1,50)),1,100))
numerator <- sum(v)
denominator <- length(v)
mean_of_vector <- numerator/denominator
print('My vector is')
print(v)
print('The mean of my vector is')
print(mean_of_vector)

```

## Problem 2c
###### In the R console, I typed the following: install.packages('dplyr')


## Problem 3
```{r}
x <- data.frame('1' = c('A','B','C','D'), '2' = c('D','E','F','G'))
View(x)
```

